{% set version = "2.2" %}

package:
  name: pyvirtualdisplay
  version: {{ version }}

source:
  fn: pyvirtualdisplay-{{ version }}.tar.gz
  url: https://github.com/ponty/PyVirtualDisplay/archive/{{ version }}.tar.gz
  sha256: 68d05685e6257972134f34b49a66b3277f593fe8c094fd27f420b7f50ff4a1b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - easyprocess
    - pillow

test:
  imports:
    - pyvirtualdisplay

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: python wrapper for Xvfb, Xephyr and Xvnc

extra:
  recipe-maintainers:
    - ReimarBauer
