{% set version = "1.0" %}

package:
  name: pyvirtualdisplay
  version: {{ version }}

source:
  fn: pyvirtualdisplay-{{ version }}.tar.gz
  url: https://github.com/ponty/PyVirtualDisplay/archive/{{ version }}.tar.gz
  sha256: 382a65c42bff91dfff40787ccd8bc31067662a41e55c82fd912891a5da4199c1

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - easyprocess

test:
  imports:
    - pyvirtualdisplay

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: python wrapper for Xvfb, Xephyr and Xvnc

extra:
  recipe-maintainers:
    - ReimarBauer
