{% set version = "2.0" %}

package:
  name: pyvirtualdisplay
  version: {{ version }}

source:
  fn: pyvirtualdisplay-{{ version }}.tar.gz
  url: https://github.com/ponty/PyVirtualDisplay/archive/{{ version }}.tar.gz
  sha256: ec6d78a08bcbb68611ed720ddd656d44f80512d79e9cee565627c439c493c47a

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - easyprocess

test:
  imports:
    - pyvirtualdisplay

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: python wrapper for Xvfb, Xephyr and Xvnc

extra:
  recipe-maintainers:
    - ReimarBauer
